// Code generated by protoc-gen-wrap. DO NOT EDIT.
package example

import (
	"math/big"
	ec "github.com/ethereum/go-ethereum/common"
)

// true
type SomeMsgWrap struct {
	*SomeMsg
	UserWrap  ec.Address
	AmtWrap   *big.Int
	RootWrap  ec.Hash
	DeltaWrap *big.Int
}
